name       : solidity
version    : 0.8.11
release    : 1
homepage   : https://soliditylang.org
source     :
    - https://github.com/ethereum/solidity/releases/download/v0.8.11/solidity_0.8.11.tar.gz : b67df542cc19f4181a07050950e235f60a6dcc8018529335701384e632947b5a
license    : GPL-3.0-or-later
component  : programming
summary    : Solidity, the smart contract programming language.
description: |
    Solidity is a statically typed, contract-oriented, high-level language for implementing smart contracts on the Ethereum platform.
networking : yes
builddeps  :
    - pkgconfig(z3)
    - libboost-devel
setup      : |
    %cmake -B build -DUSE_CVC4=OFF -DTESTS=OFF
build      : |
    %make -C build
install    : |
    %make_install -C build
